# Running goreleaser with the snapshot flag allows us to run some custom validations
# on our build without publishing: https://goreleaser.com/customization/snapshots/
# TODO -- verify docker builds
# TODO -- add so it only runs when we update the goreleaser directory.

name: test-gorelease

on:
  push:
    paths:
    - '.goreleaser/**'
  pull_request:
    paths:
    - 'goreleaser/**'

# TODO -- it would be nice if we could verify pulling the docker images from other machines
# by actually publishing the docker image to a test namespace
jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      # https://goreleaser.com/customization/docker_manifest/
      DOCKER_CLI_EXPERIMENTAL: "enabled"

    steps:
      - name: Code checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - name: Run GoReleaser Snapshot
        uses: goreleaser/goreleaser-action@v2
        with:
          version: v0.184.0
          args: release -f .goreleaser/linux.yml --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_SECRET: ${{ secrets.ARTIFACTORY_SECRET }}
